export enum CardType {
    DEBIT = "DEBIT",
    CREDIT = "CREDIT",
}

export enum CardNetworkType{
    VISA = "VISA",
    MASTERCARD = "MASTERCARD",
}

export enum ATMState {
    // These are the running states of the ATM machine 
    READY_FOR_TRANSACTION_STATE = "READY_FOR_TRANSACTION_STATE", 
    READING_CARD_DETAILS_STATE = "READING_CARD_DETAILS_STATE",  
    CHOOSE_OPTION_STATE = "CHOOSE_OPTION_STATE",
    READING_WITHDRAW_MONEY_STATE = "READING_WITHDRAW_MONEY_STATE", 
    BALANCE_INQUIRY_STATE = "BALANCE_INQUIRY_STATE", 
    DISPENSE_MONEY_STATE = "DISPENSE_MONEY_STATE", 
    EJECT_CARD_STATE = "EJECT_CARD_STATE", 
}